$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$docsRoot = Join-Path $repoRoot "docs"
$autoGeneratedRoot = Join-Path $docsRoot "auto-generated"
$openApiDir = Join-Path $autoGeneratedRoot "openapi"
$dotnetApiDir = Join-Path $autoGeneratedRoot "dotnet-api"
$swaggerUiDir = Join-Path $autoGeneratedRoot "swagger-ui"
$siteDir = Join-Path $repoRoot "artifacts/docs/site"
$localApiProject = Join-Path $repoRoot "backend/src/KnowledgeApp.LocalApi/KnowledgeApp.LocalApi.csproj"
$docfxConfig = Join-Path $docsRoot "docfx.json"
$swaggerUiPackageDir = Join-Path $repoRoot "node_modules/swagger-ui-dist"
$docsRuntimeRoot = Join-Path $repoRoot "artifacts/docs/runtime"

if (-not (Test-Path $swaggerUiPackageDir)) {
    throw "swagger-ui-dist is not installed. Run pnpm install before building docs."
}

New-Item -ItemType Directory -Force $autoGeneratedRoot | Out-Null
Get-ChildItem -LiteralPath $autoGeneratedRoot -Force |
    Where-Object { $_.Name -notin @("README.md", ".gitkeep") } |
    Remove-Item -Recurse -Force

New-Item -ItemType Directory -Force $openApiDir, $dotnetApiDir, $swaggerUiDir, $siteDir | Out-Null

$env:LocalRuntime__DataPath = Join-Path $docsRuntimeRoot "app/data"
$env:LocalRuntime__DatabasePath = Join-Path $docsRuntimeRoot "app/data/knowledge-app-docs.db"
$env:LocalRuntime__FilesPath = Join-Path $docsRuntimeRoot "app/files"
$env:LocalRuntime__IndexPath = Join-Path $docsRuntimeRoot "app/indexes"
$env:LocalRuntime__LogsPath = Join-Path $docsRuntimeRoot "app/logs"
$env:Ai__EmbeddingProvider = "Stub"
$env:Ai__RuntimePath = Join-Path $docsRuntimeRoot "ai/bin/llama-server.exe"
$env:Ai__ModelsPath = Join-Path $docsRuntimeRoot "ai/models"
$env:IngestionWorker__Enabled = "false"

dotnet tool restore
dotnet build $localApiProject --configuration Release --no-incremental /p:OpenApiGenerateDocuments=true /p:OpenApiDocumentsDirectory="$openApiDir"

$generatedOpenApi = Get-ChildItem -LiteralPath $openApiDir -Filter "*.json" |
    Sort-Object LastWriteTimeUtc -Descending |
    Select-Object -First 1

if ($null -eq $generatedOpenApi) {
    throw "LocalApi build did not generate an OpenAPI JSON document."
}

$openApiJson = Join-Path $openApiDir "openapi.json"
if ($generatedOpenApi.FullName -ne $openApiJson) {
    Move-Item -LiteralPath $generatedOpenApi.FullName -Destination $openApiJson -Force
}

Copy-Item (Join-Path $swaggerUiPackageDir "swagger-ui.css") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "swagger-ui-bundle.js") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "swagger-ui-standalone-preset.js") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "favicon-16x16.png") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "favicon-32x32.png") $swaggerUiDir -Force

dotnet tool run docfx metadata $docfxConfig

$dotnetApiToc = Join-Path $dotnetApiDir "toc.yml"
if (-not (Test-Path $dotnetApiToc)) {
    throw "DocFX metadata did not generate .NET API table of contents."
}

if (Test-Path $siteDir) {
    Remove-Item -LiteralPath $siteDir -Recurse -Force
}

dotnet tool run docfx build $docfxConfig

Write-Host "Documentation site generated at $siteDir"
