$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$docsRoot = Join-Path $repoRoot "docs"
$autoGeneratedRoot = Join-Path $docsRoot "auto-generated"
$openApiDir = Join-Path $autoGeneratedRoot "openapi"
$dotnetApiDir = Join-Path $autoGeneratedRoot "dotnet-api"
$swaggerUiDir = Join-Path $autoGeneratedRoot "swagger-ui"
$siteDir = Join-Path $repoRoot "artifacts/docs/site"
$docfxConfig = Join-Path $docsRoot "docfx.json"
$swaggerUiPackageDir = Join-Path $repoRoot "node_modules/swagger-ui-dist"
$docsRuntimeRoot = Join-Path $repoRoot "artifacts/docs/runtime"
$openApiGenerator = Join-Path $repoRoot "scripts/openapi/generate-local-api-spec.ps1"

if (-not (Test-Path $swaggerUiPackageDir)) {
    throw "swagger-ui-dist is not installed. Run pnpm install before building docs."
}

if (-not (Test-Path $openApiGenerator)) {
    throw "OpenAPI generation script was not found at $openApiGenerator."
}

New-Item -ItemType Directory -Force $autoGeneratedRoot | Out-Null

Get-ChildItem -LiteralPath $autoGeneratedRoot -Force |
    Where-Object { $_.Name -notin @("README.md", ".gitkeep") } |
    Remove-Item -Recurse -Force

New-Item -ItemType Directory -Force $openApiDir, $dotnetApiDir, $swaggerUiDir, $siteDir |
    Out-Null

dotnet tool restore

$openApiJson = Join-Path $openApiDir "openapi.json"

& $openApiGenerator `
    -RepositoryRoot $repoRoot `
    -OutputFile $openApiJson `
    -RuntimeRoot $docsRuntimeRoot `
    -RuntimeDatabaseFileName "knowledge-app-docs.db"

Copy-Item (Join-Path $swaggerUiPackageDir "swagger-ui.css") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "swagger-ui-bundle.js") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "swagger-ui-standalone-preset.js") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "favicon-16x16.png") $swaggerUiDir -Force
Copy-Item (Join-Path $swaggerUiPackageDir "favicon-32x32.png") $swaggerUiDir -Force

dotnet tool run docfx metadata $docfxConfig

$dotnetApiToc = Join-Path $dotnetApiDir "toc.yml"

if (-not (Test-Path $dotnetApiToc)) {
    throw "DocFX metadata did not generate .NET API table of contents."
}

if (Test-Path $siteDir) {
    Remove-Item -LiteralPath $siteDir -Recurse -Force
}

dotnet tool run docfx build $docfxConfig

Write-Host "Documentation site generated at $siteDir"
