package com.localmind.fileservice.common.error;

public enum ErrorCode {
  FILE_NOT_FOUND,
  FILE_UPLOAD_EMPTY,
  FILE_SIZE_EXCEEDED,
  UNSUPPORTED_FILE_EXTENSION,
  STORAGE_WRITE_FAILED,
  STORAGE_READ_FAILED,
  STORAGE_DELETE_FAILED,
  PROCESSING_JOB_NOT_FOUND,
  VALIDATION_FAILED,
  INTERNAL_SERVER_ERROR
}
