import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class DevicesService {
  constructor(private readonly prisma: PrismaService) {}

  async trackDevice(
    userId: string,
    metadata: {
      deviceName?: string;
      platform?: string;
      userAgent?: string;
      ipAddress?: string;
    },
  ) {
    // Basic fingerprinting using userAgent + IP for demo purposes
    // In real app, consider using a true device ID generated by the client
    const existingDevice = await this.prisma.device.findFirst({
      where: {
        userId,
        userAgent: metadata.userAgent,
        ipAddress: metadata.ipAddress,
      },
    });

    if (existingDevice) {
      return this.prisma.device.update({
        where: { id: existingDevice.id },
        data: { lastActive: new Date() },
      });
    }

    return this.prisma.device.create({
      data: {
        userId,
        ...metadata,
      },
    });
  }
}
